# Generated by Django 5.2.3 on 2026-03-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsDB', '0004_supplier_admin_last_login_cashier_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='AccountsDB.manager')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='AccountsDB.supplier')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('manager', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('manager', 'Manager'), ('supplier', 'Supplier')], max_length=10)),
                ('sender_id', models.IntegerField()),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AccountsDB.chatroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
