# Generated by Django 5.2.3 on 2026-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatasetDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Barcode')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock Quantity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
