# Generated by Django 5.2.3 on 2026-03-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatasetDB', '0002_cashier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier_product',
            name='threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Reorder Threshold'),
        ),
    ]
