# Generated by Django 5.2.3 on 2025-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (₹)')),
                ('in_stock', models.IntegerField(default=0, verbose_name='Current Stock')),
                ('min_stock_level', models.IntegerField(default=10, verbose_name='Minimum Stock Level')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Brand')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
